### PR TITLE
Some editorial fixes

### PR DESCRIPTION
**Pull request by sigiesec**
***
<a href="https://pr-preview.s3.amazonaws.com/sigiesec/IndexedDB/pull/284.html" title="Last updated on Jul 5, 2019, 12:03 PM UTC (2231495)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IndexedDB/284/de6cba4...sigiesec:2231495.html" title="Last updated on Jul 5, 2019, 12:03 PM UTC (2231495)">Diff</a>

### CODE REVIEW

**Comment by sigiesec** [comment]
@inexorabletash np. I suppose these changes can be regarded non-substantial, right?

**Comment by inexorabletash** [comment]
Yeah. I can hit the magic button when I'm back at work next week if no-one beats me to it.

**Comment by marcoscaceres** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by inexorabletash** [comment]
Thanks @marcoscaceres ! And @sigiesec for finding the issues in the first place. More please!

**Pull request merged**
