### PR TITLE
Sketch out spec text for transaction durability option

### LINKED ISSUE #50: Define flush-to-disk guarantees and control
Define flushing guarantees and expose control
e.g. make transactions not flush-to-disk by default, but introduce a "readwriteflush" mode or {flush: true} option

Currently, FF does not flush (but wants an option), Chrome always flushes.

### PR DESCRIPTION
**Pull request by inexorabletash**
Closes #50

The following tasks have been completed:

 * [x] Confirmed there are no ReSpec/BikeShed errors or warnings.
 * [x] Modified Web platform tests ([tentative tests](https://github.com/web-platform-tests/wpt/blob/master/IndexedDB/transaction-relaxed-durability.tentative.any.js))

Implementation commitment:

 * [ ] WebKit (???)
 * [x] Chromium (https://www.chromestatus.com/feature/5730701489995776)
 * [ ] Gecko (???)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/IndexedDB/pull/301.html" title="Last updated on Nov 26, 2019, 7:37 PM UTC (27681a2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/IndexedDB/301/95d8712...27681a2.html" title="Last updated on Nov 26, 2019, 7:37 PM UTC (27681a2)">Diff</a>

### CODE REVIEW

**Comment by pwnall** [comment]
I don't think we discussed whether we'd want options to be an alternative to mode. Worth figuring this out before we commit to the API shape described here?

**Comment by asutherland** [comment]
Excellent phrasing on the spec text.  I don't think I personally have an opinion on the signature other than the overload stuff at https://heycam.github.io/webidl/#idl-overloading is complicated and the presence of optional arguments complicates things.  (Specifically, in our attempt to eliminate Firefox's overload of `open` and use-counting we've run into things.)  It seems reasonable to me to stick to not having any overloads if we think we can avoid future overloads, which would be an argument for the current pull request's approach.  If we'll want overloads in the future, we maybe should consider all of this more strongly.

**Comment by inexorabletash** [comment]
> options to be an alternative to mode

As a third argument, it's a graceful fallback for older browsers - silently ignored. Which is great IMHO since it's just a hint. And it avoids an overload, which we're generally allergic to. Open to counter-arguments, though.

A few things the patch needs:

* It needs to say "The durability hint is one of the following:"
* It needs to explicitly say that the default for transaction objects is "default" (e.g. for versionchange transactions)
* The text should not just be tucked in to the bottom of the transaction definition - it might make more sense a few paragraphs up.
* Do we want to throw if a non-default option is set for readonly transactions? IMHO: no.

**Comment by pwnall** [comment]
Do we want to throw if a non-default option is set for readonly transactions? -- I agree with you.

It makes more sense to me that all transactions have a durability property that behaves in the same way. Since it's intended to be a hint, the hint will be ignored in read-only transactions.

**Comment by inexorabletash** [comment]
Any objections to going forward with merging this?

**Comment by asutherland** [comment]
I tried to be cool in December and use a thumbs-up emoji, but I don't think that generated a notification, so to clarify, I'm good with merging this.

**Comment by inexorabletash** [comment]
Hah! Thanks for remembering.

**Pull request merged**
