### PR TITLE
open/deleteDatabase should throw on opaque origin

### PR DESCRIPTION
**Pull request by inexorabletash**
Context: https://github.com/w3c/IndexedDB/issues/148

Needs tests.

### CODE REVIEW

**Comment by inexorabletash** [comment]
The text _"the origin of the global scope used to access this IDBFactory"_ could almost certainly be improved, but it's what was there already.

**Comment by inexorabletash** [comment]
@aliams - could you review?

**Comment by foolip** [comment]
Tests for this are at https://github.com/w3c/web-platform-tests/pull/4832, it would be ideal if the spec change is merged before the tests, but that's blocking Chromium's test export process so I'll probably go ahead and merge that first. It will likely be reverted though if the test change isn't merged soon after.

**Comment by inexorabletash** [comment]
I guess we merge spec changes before landing test changes?

@foolip - can you review https://github.com/w3c/web-platform-tests/pull/4829 ?

**Comment by foolip** [comment]
OK, so there were other tests as well. I'll review those.

**Pull request merged**
