### PR TITLE
Change "index handle" -> "object store handle" references within `IDB…

### PR DESCRIPTION
**Pull request by brettz9**
…ObjectStore.getKey`

### CODE REVIEW

**Comment by inexorabletash** [comment]
Apologies - this repo should have automatic IPR checks set up with it. Working on it...

This change would be considered non-substantive, but I want to get the check in place first.

Thanks for pointing out the issue, @brettz9 !

**Comment by brettz9** [comment]
Sure... Let me know if there's already something I can sign (or I can wait for checks) in case any of my PRs do become substantive (at this point at least, I doubt it).

**Comment by inexorabletash** [comment]
Applied a similar change in 57069af90471b544807d282ef67585c1bd1f598f

For tracking purposes, going forward can you file issues instead of or in addition to the PRs? Often it will be easier to make the change directly and I'd prefer to have an issue to link to so others can understand the problem.

**Comment by inexorabletash** [comment]
And thanks again!

**Comment by brettz9** [comment]
Sure (will try to remember)

**Pull request closed without merging**
