### PR TITLE
Set request result/done flag appropriately in open/delete

### PR DESCRIPTION
**Pull request by inexorabletash**
For https://github.com/w3c/IndexedDB/issues/161:

* When an open or delete succeeds the done flag should be set.
* When an open fails aborts, the request's result should be cleared.

I need to verify we have WPT coverage for this.

@brettz9 - can you review?

### CODE REVIEW

**Comment by inexorabletash** [comment]
WPT coverage was lacking! Fortunately, Chrome and Firefox already pass.

New tests: https://github.com/w3c/web-platform-tests/pull/5899

**Comment by brettz9** [comment]
I think this PR covers it well...

However, besides if you wanted to add that invisible step to unset the done flag for successful transactions, there is the case also of `result` always needing to return `undefined` (per the `result` getter) when there is an error, so I don't know if you wanted to make that explicit for `open` and `deleteDatabase`.

For example, for the following in the steps to open a database, "If connection was closed, create and return a newly created "AbortError" DOMException and abort these steps.", this isn't followed by setting the `result` to `undefined` (as now is the case with your PR if the steps to abort are triggered). And perhaps this could also occur with other errors of the database (like `UnknownError`) that didn't cause an abort.

I think mention of setting the request result to `undefined` could be added close to the end of `open()` and `deleteDatabase()` when the request's `error` properties are set.

**Comment by inexorabletash** [comment]
Thanks!

> ...if you wanted to add that invisible step to unset the done flag..

Rather than doing this I updated the non-normative comment so it doesn't claim the done flag will be unset in all cases.

> ...If connection was closed... this isn't followed by setting the result to undefined

Great catch! I addressed this as you suggested...

> .. setting the request result to undefined could be added close to the end of open() and deleteDatabase() when the request's error properties are set.

... but only for open(), since deleteDatabase() doesn't have a path where the request would be "done" and get a result/error except at the very end.

**Comment by brettz9** [comment]
> ... but only for open(), since deleteDatabase() doesn't have a path where the request would be "done" and get a result/error except at the very end.

Oh yes... I c...there will be nothing to clear...

So considering the `result` getter's definition:

> The result attribute’s getter must throw an "InvalidStateError" DOMException if the done flag is unset. Otherwise, the attribute’s getter must return the result of the request, or undefined if the request resulted in an error.

...upon a `deleteDatabase` error, there will be no `InvalidStateError ` error on retrieval of the `result` property as the done flag has been set by the end of `deleteDatabase`, and the getter is already spec'd to return `undefined` if there is an error, so there is no need to explicitly set it (with nothing prior on the delete request to overwrite)...

**Comment by inexorabletash** [comment]
Yes. It could be made a bit more rigorous, as "if the request resulted in an error" is bit of action-at-a-distance. But for this CL... everything look good?

**Comment by brettz9** [comment]
Yup, all good, thanks!

**Pull request merged**
