### PR TITLE
Do not automatically throw in `continuePrimaryKey` for key == cursor position

### PR DESCRIPTION
**Pull request by brettz9**
Builds on prior PR related to `continuePrimaryKey`.

For `continuePrimaryKey`, do not automatically throw as with `continue`  when the key is equal to the cursor's position (the following steps will instead check that possibility, depending on the `primaryKey` and object store position)

### CODE REVIEW

**Comment by brettz9** [comment]
Oh, and one more thing I'm not sure how you might want fixed... In the bolded parts here:

> 15. If key is equal to this cursor’s position and primaryKey is **less than** or **equal to** this cursor’s object store position and this cursor’s direction is "next" or "nextunique", throw a DataError.
> 16. If key is equal to this cursor’s position and primaryKey is **greater than** or **equal to** this cursor’s object store position and this cursor’s direction is "prev" or "prevunique", throw a DataError.

...these link to comparisons based on *key* whereas I think they should be comparing to value.

**Comment by brettz9** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Comment by inexorabletash** [comment]
Applied similar change in fdd02cf8c61025c9c79b0e193db623d12ccb3169

Thanks!

**Comment by inexorabletash** [comment]
Oh, missed the "one more thing..."

The phrases you bold are the algorithms for comparing keys in general. The inputs are the _primaryKey_ argument and the cursor's _object store position_ which are both keys.

**Comment by brettz9** [comment]
Thanks for your response--I've since added issue #106 so will reply there.

**Pull request closed without merging**
