### PR TITLE
Parity between key retrieval steps and type conversions

### PR DESCRIPTION
**Pull request by inexorabletash**
For https://github.com/w3c/IndexedDB/issues/107

@brettz9 - could you take a look and see if this matches your expectations?

### CODE REVIEW

**Comment by inexorabletash** [comment]
Hrm, wonder what's up with the IPR check. Ash-Nagz claims "inexorabletash is not in the right groups" but also shows I'm in Web Platform Working Group...

**Comment by inexorabletash** [comment]
@siusin - do you know what's up with the IPR check failure?

**Comment by siusin** [comment]
There may be a bug in the system - I have pinged @dontcallmedom about it.

**Comment by inexorabletash** [comment]
Whoah, sorry, branched this off of another PR...

**Comment by inexorabletash** [comment]
Okay, diff should be more manageable. @brettz9  or @aliams - can you take a peek?

**Comment by aliams** [comment]
LGTM

**Pull request merged**
